site_name: Изменения 1С

nav:
    - Моя Бухгалтерия: 
        - Изменения: index.md
        - Новые участки: new-mb.md
    - Моя Зарплата:
        - Моя зарплата: zup.md
    - АКомплекс:
        - АКомплекс: akompl.md
    - СКУД:
        - Система контроля доступа: perco.md
    - Резервное копирование:
        - Резервное копирование: copy.md

theme: 
    name: readthedocs
    locale: ru
